before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - lbrapid@gmail.com
    - ryan@spreecommerce.com
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
